baseURL = 'https://example.com/'
languageCode = 'zh-CN' 
title = '丘丘人'                    # 网站名称
theme = "show"                # 主题
archetypeDir = "themes/show/archetypes"

[markup.goldmark.renderer]
  unsafe = true

[params]
  description = "使用show主题搭建的静态网页"  # 网站描述信息
  keywords = "Hugo, 静态网站, 博客, 示例"        # 网站关键词

[assets]
  postCSS = true  # 启用 PostCSS 支持，包括 SCSS 处理

[build]
  writeStats = true

[outputs]
home = ["HTML", "RSS", "JSON"]
