baseURL = 'https://hugotheme-show.netlify.app/'
languageCode = 'zh-CN' 
title = '丘丘人'                    # 网站名称
theme = "show"                # 主题
archetypeDir = "themes/show/archetypes"

paginate = 5  # 设置每页显示 5 篇文章

[markup.goldmark.renderer]
  unsafe = true

[params]
  description = "使用show主题搭建的静态网页"  # 网站描述信息
  keywords = "Hugo, 静态网站, 博客, 示例，演示页面"        # 网站关键词
  name = "丘丘人"
  signature = "网络加载错误，请稍后再试..."

[assets]
  postCSS = true  # 启用 PostCSS 支持，包括 SCSS 处理



[build]
  writeStats = false

[outputs]
home = ["HTML", "RSS", "JSON"]